[package]
name = "rud"
version = "0.1.0"
authors = ["NaokiM03 <naokim03.lib+dev@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
